version: "3.6"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
  pg:
    container_name: pg
    image: postgres:13
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/London
    ports:
      - "9432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]