app_name: books
port: 8002
logs:
  level: info
  format: console
postgres:
  read:
    host: localhost
    port: 9432
    user: postgres
    password: postgres
    database: books
    max_open_cons: 10
    max_idle_cons: 5
    prefer_simple_protocol: false
    ssl_mode: disable
    timezone: Europe/Kiev
  write:
    host: localhost
    port: 9432
    user: postgres
    password: postgres
    database: books
    max_open_cons: 10
    max_idle_cons: 5
    prefer_simple_protocol: false
    ssl_mode: disable
    timezone: Europe/Kiev